services:
    student.statistics.github:
        class: StudentBundle\Statistics\GithubService
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%github_client_id%'
            - '%github_client_secret%'
